adding:
  dependencies:
    config:
      - field.field.taxonomy_term.subcategory.field_child_s_age
  content:
    field_child_s_age:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 2
      region: content
removing:
  dependencies:
    config:
      - field.field.taxonomy_term.subcategory.field_child_age
  content:
    field_child_age:
      type: entity_reference_label
      label: above
      settings:
        link: true
      weight: 2
