label: Files
display:
  default:
    display_title: Default
    display_options:
      title: Files
      fields:
        filename:
          label: Name
        filemime:
          label: 'MIME type'
        status:
          label: Status
        count:
          format_plural_string: !!binary MSBwbGFjZQNAY291bnQgcGxhY2Vz
      exposed_form:
        options:
          submit_button: Filter
          exposed_sorts_label: 'Sort by'
      filters:
        filemime:
          expose:
            label: 'MIME type'
        status:
          expose:
            label: Status
  page_1:
    display_options:
      menu:
        title: Files
  page_2:
    display_options:
      fields:
        type:
          label: 'Entity type'
